baseURL = "https://zupit.github.io/opensource-tech-radar/"
languageCode = "en-us"
title = "Tech radar"
publishDir = "docs"
relativeURLs = true
canonifyURLs = true

offlineSearchSummaryLength = 70

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10

  [languages.pt-BR]
    contentDir = 'content/pt-BR'
    languageName = 'Português'
    weight = 20

