baseURL = "/"

title = "Tech Radar - Opensource - Zup I.T"

publishDir = "docs"

relativeURLs = true
canonifyURLs = true

theme = ["techradar"]

[params]
offlineSearchMaxResults = 7

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10

  [languages.pt-BR]
    contentDir = 'content/pt-BR'
    languageName = 'Português'
    weight = 20

