name: Pull request Validation

on:
  pull_request:
    branch: [main]
    tags-ignore:
      - '*.*' 
    paths-ignore: 
      - .\docs

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
          fetch-depth: 0    

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.76.4'
          extended: true

      - name: Build
        run: hugo -D --minify -b https://opensource.zup.com.br/radar
