name: Pull request Validation

on:
  pull_request:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.76.4'
          extended: true

      - name: Build
        run: hugo -D
